### ISSUE TITLE
prisma import update, expandables clean up

### ISSUE THREAD

**Issue by atherdon** [atherdon/dash-back#123]
cc @dennyunited

я вроде видео про импорт скинул в телеграмм, скажите у вас есть ко мне вопросы?
с моей стороны - думаю можно начинать, заодно и протестим наш setup на heroku

Плюс, мы можем добавить больше exceptions в импорт, чтобы проще было ловить ошибки

**Comment by dennyunited** [comment]
@atherdon взял задачу в работу

**Comment by atherdon** [comment]
поидее там все просто должно быть - сделайте форк и начнем кодить 
я заодно узнаю что Вадим во фронте собирался делать - может скоро соединим back & front общей задачей

**Comment by dennyunited** [comment]
@atherdon воспросы по задаче импорта данных 
1. Модель данных для Expandable должна содержать обязательными аттрибуты
 - id
 - key
 -  name
 - address
 - articles
 - created
 - updated
2. Данные ли конфигурационные файлы являются актуальной ли версией [expandable2](https://github.com/atherdon/dash-back/blob/main/data/expandable/expandable2.js) и [expandable3](https://github.com/atherdon/dash-back/blob/main/data/expandable/expandable3.js)
3. Необходимо добиться того, что операция импорта данных в prisma из конфигурационных файлов завершалась успешно ?

**Comment by atherdon** [comment]
cc @dennyunited

**Comment by atherdon** [comment]
в видео я говорил что нужно будет разобраться как работает призмовский codegen(я незнаю как он работает), но т.к. это ORM - должно бы просто - есть какой то конфиг, типы и т.д. при запуске миграции должна обновляться схема и подтягивать все изменения, которые были внесены.

посмотрите тут https://www.prisma.io/docs/concepts/components/prisma-migrate
штука как я понял достаточно удобная сс @dennyunited

**Comment by dennyunited** [comment]
@atherdon как проводить миграции данных в моделях с рабочей дев станции я разабролся

**Comment by dennyunited** [comment]
@atherdon фикс проведен в комминте https://github.com/atherdon/dash-back/commit/f69fb1f19cbbfbe19d6ee756884aa3e129214635. какие следующие задачи по проекту?

**Comment by dennyunited** [comment]
Fixed
