### ISSUE TITLE
can we completely remove this `address` field, please?

### ISSUE THREAD

**Issue by atherdon** [atherdon/dash-back#127]
can we completely remove this `address` field, please?

_Originally posted by @atherdon in https://github.com/atherdon/dash-back/pull/126#discussion_r606115372_

**Comment by atherdon** [comment]
cc @dennyunited

**Comment by dennyunited** [comment]
This might lead to unexpected behavior.

       Please make sure they have the same version.

       src/graphql/resolvers/expandable/deleteOne.ts(25,21): error TS2339: Property 'address' does not exist on type 'Expandable'.

       src/graphql/resolvers/expandable/getMany.ts(19,23): error TS2339: Property 'address' does not exist on type 'Expandable'.

       src/graphql/resolvers/expandable/getOne.ts(28,21): error TS2339: Property 'address' does not exist on type 'Expandable'.

       src/graphql/resolvers/expandable/postOne.ts(21,7): error TS2322: Type '{ name: string; key: number; address: string; articles: string; }' is not assignable to type '(Without<ExpandableUncheckedCreateInput, ExpandableCreateInput> & ExpandableCreateInput) | (Without<...> & ExpandableUncheckedCreateInput)'.

         Object literal may only specify known properties, and 'address' does not exist in type '(Without<ExpandableUncheckedCreateInput, ExpandableCreateInput> & ExpandableCreateInput) | (Without<...> & ExpandableUncheckedCreateInput)'.

       src/graphql/resolvers/expandable/postOne.ts(30,21): error TS2339: Property 'address' does not exist on type 'Expandable'.

       src/graphql/resolvers/expandable/updateOne.ts(23,7): error TS2322: Type '{ name: string | undefined; key: number | undefined; address: string | undefined; articles: string | undefined; updated: Date; }' is not assignable to type '(Without<ExpandableUncheckedUpdateInput, ExpandableUpdateInput> & ExpandableUpdateInput) | (Without<...> & ExpandableUncheckedUpdateInput)'.

         Object literal may only specify known properties, and 'address' does not exist in type '(Without<ExpandableUncheckedUpdateInput, ExpandableUpdateInput> & ExpandableUpdateInput) | (Without<...> & ExpandableUncheckedUpdateInput)'.

       src/graphql/resolvers/expandable/updateOne.ts(33,21): error TS2339: Property 'address' does not exist on type 'Expandable'.

       src/prisma/fill/fillExpandable.ts(22,34): error TS2339: Property 'parentCategory' does not exist on type '{ key: number; name: string; articles: string[]; }'.

error Command failed with exit code 2.

Думаю, данное поле address целесообразно удалять из всех файлов лога деплоя

**Comment by atherdon** [comment]
все доп файлы должны перегенерироваться с помощью prisma

@vadim9999 ты умеешь пользховаться codegen для бекенда?

**Comment by atherdon** [comment]
https://medium.com/tomorrowapp/using-prisma-with-graphql-codegen-eed022c13749

**Comment by dennyunited** [comment]
> https://medium.com/tomorrowapp/using-prisma-with-graphql-codegen-eed022c13749

thanks

**Comment by dennyunited** [comment]
@atherdon фикс проведен в комминте https://github.com/atherdon/dash-back/commit/f69fb1f19cbbfbe19d6ee756884aa3e129214635. какие следующие задачи по проекту?
