### ISSUE TITLE
Roles data

### ISSUE THREAD

**Issue by atherdon** [atherdon/dash-back#36]
нужно ли мне сделать список ролей, чтобы вы их залили в базу сразу? я могу сделать обычный js array и добавить его в папку data 

_Originally posted by @atherdon in https://github.com/atherdon/dash-back/discussions/11#discussioncomment-358718_

**Comment by atherdon** [comment]
1. admin / developer
2. Editor - can see most of the things. But we can hide pages that not important. Like detailed stats or something
3. Managed Editor - this role should include Editor access, but also be able to view some pages, that can give more company-wide perspective. Like how much articles was published per year. Or something else :)
4. Junior Editor - will have their own pages. Mostly a simple version of editor role
5. contributing editor. similar flow to junior editor. Feature for a future.
6. top-authors. similar to junior editor and contributing editor
7. freelancer
8. managed-account

**Comment by kolserdav** [comment]
Добавил в версию `3.3.1`
Конфигурация ролей в `src/prisma/config/roles.json`
пока что сделал что он каждый запуск сервера перезаписывает в базе таблицу `Role` из файла концигураций, потом если потребуется можно в отдельный скрипт вынести, чтобы не рестартить сервер если надо роли поменять.

**Comment by atherdon** [comment]
спасибо, тогда пока закрываю
