### ISSUE TITLE
schema changes before releasing alpha version of frontend

### ISSUE THREAD

**Issue by atherdon** [atherdon/dash-back#61]
### add Edited stories schema. logic similar to topAuthors/Evergreen
в этой части я просто предлагаю скопировать одну из старых схем и "просто" ее переменовать.
когда мы с Вадимом поняли что бекенд дает нам возможность уже показать проект редакторам - мы начали убирать все лишнее. В этот момент я понял что у нас отсутствует секция с общими статьями. 
вот как выглядит админка в альфа-версии. деплоили на heroku - могу дать доступы посмотреть. Данные есть везде, кроме "Edited Stories"
![image](https://user-images.githubusercontent.com/1469198/108829536-f8a2d380-75d0-11eb-93da-14e40afa7086.png)

сейчас будет достаточно, чтобы данные были похожими на данные из topAuthors/Evergreen
![image](https://user-images.githubusercontent.com/1469198/108829656-1d974680-75d1-11eb-851d-61cc44ed5a4f.png)

---

### I need to update expandable, so it will meet our requirements.
Текущая версия js массива - это просто fake-data которую мы взяли из примера. Я хочу заменить эти данные, чтобы нам было удобнее работать. примером, который есть сейчас, является kanban доска, в которой один таск - это просто title а внутри есть список статей.
![image](https://user-images.githubusercontent.com/1469198/108829920-7070fe00-75d1-11eb-9094-41179be42fbe.png)
![image](https://user-images.githubusercontent.com/1469198/108829979-7ebf1a00-75d1-11eb-85a7-70f204539439.png)

скоро сделаю пример как js array и покажу вам

---

### counters that Vadim wants(need to link with task)
Вадим хочет выводить counter для каждого типа статей, чтобы было видно, сколько статей еще не обработано.
например если есть необработаных 40 статей для брендов - это плохо, можно вывести красный warning. если 10 - то окей и т.д. Я так понимаю что Вадиму просто нужны методы, которые вернут сколько записей в базе для topAuthors/Evergreen/Edited
![image](https://user-images.githubusercontent.com/1469198/108830308-e07f8400-75d1-11eb-9b5f-9bd57cc6686e.png)

---

### обновление upload-forms, sync с изменениями в backend
После того, как мы добавим "Edited Stories", изменим expandable - нужно будет внести изменения в upload form - чтобы Марина могла эти данные тоже сохранять в нашу базу.

сс @kolserdav

**Comment by atherdon** [comment]
я обновил данные для expandable.
- https://github.com/atherdon/dash-back/blob/main/data/expandable2.js
- https://github.com/atherdon/dash-back/blob/main/data/expandable3.js

**Comment by kolserdav** [comment]
1. Переименовать Brands в Evergreen
2. Поменять схему для expandable , по новым файлам.
3. Добавить какие-то фильтры на некоторые схемы getMany. ? И чтобы возвращал количество
4. Изменения бекенда обновить в forms
Правильно понимаю? 3 пункт не совсем понял

**Comment by atherdon** [comment]
1. я думал мы уже это сделали
2. да, верно
3. посути нам нужен метод count(). если pseudo-code: topAuthors.count(), evergreen.count(), edited.count()
4. да, нам важно будет иметь возможность добавлять edited articles и наполнять expandable

cc @kolserdav

**Comment by kolserdav** [comment]
1. Мы добавляли Articles клон Brands и Topauthors.  Я помню вы говорили в дискуссиях, но при обсуждении задач этого не было.

**Comment by kolserdav** [comment]
3. Количество всех записей в таблице, понятно, edited - это что?

**Comment by atherdon** [comment]
> 1. Количество всех записей в таблице, понятно, edited - это что?

Edited Stories Scheme

**Comment by kolserdav** [comment]
Она у нас есть, на основе какого файла из data?

**Comment by atherdon** [comment]
> Она у нас есть, на основе какого файла из data?

можете прстоскопировать topauthors file и переименовать его

сс @kolserdav

**Comment by kolserdav** [comment]
Получится 4 клона:
1. Top authors
2. Evergren бывший Brands
3. Article - недавно добавлена но пустая
4. Edited - которую нужно добавить
Верно?

**Comment by atherdon** [comment]
> Получится 4 клона:
> 
> 1. Top authors
> 2. Evergren бывший Brands
> 3. Article - недавно добавлена но пустая
> 4. Edited - которую нужно добавить
>    Верно?

Да. Скорее всего мы решим этот вопрос - и уберем клонов в следующем майлстоуне

**Comment by atherdon** [comment]
поидее готово. закрываю
